version: 2.1
jobs:
  build:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run:
          name: Run Cargo Build
          command: |
            sudo chmod +x build.sh
            ./build.sh
