version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  argocd-manual-sync:
    docker:
      - image: cimg/base:stable
    parameters:
      server:
        description: |
          Server IP of of ArgoCD
        type: string
      username:
        description: |
          Username for ArgoCD
        type: string
      password:
        description: |
          Password for ArgoCD
        type: string
    steps:
      - run:
          name: Install ArgoCD CLI
          command: |
            URL=https://<< parameters.server >>/download/argocd-linux-amd64
            [ -w /usr/local/bin ] && SUDO="" || SUDO=sudo
            $SUDO curl --insecure -sSL -o /usr/local/bin/argocd $URL
            $SUDO chmod +x /usr/local/bin/argocd
      - run:
          name: ArgoCD CLI login
          command: argocd login << parameters.server >> --insecure --username << parameters.username >> --password << parameters.password >>
      - run:
          name: Manual sync
          command: argocd app sync $APP_NAME
      - run:
          name: Wait for application to reach a synced and healthy state
          command: argocd app wait $APP_NAME

  argocd-configure:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Pull Updated code from repo
          command: git pull origin $CIRCLE_BRANCH
      - kubernetes/install
      - run:
          name: Update Kubeconfig Credentials
          command: |
            kubectl config set-cluster restaurant-reservation
            kubectl config set clusters.restaurant-reservation.server https://44.208.158.69:16443
            kubectl config set clusters.restaurant-reservation.certificate-authority-data $KUBE_CERT_AUTH_DATA
            kubectl config set-credentials admin --token=$KUBE_TOKEN
            kubectl config set-context restaurant-reservation --cluster=restaurant-reservation --user=admin
            kubectl config use-context restaurant-reservation
      - kubernetes/create-or-update-resource:
          resource-file-path: argocd/config.yaml

  bump-docker-tag-kustomize:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Install kustomize
          command: |
            URL=https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v4.5.2/kustomize_v4.5.2_linux_amd64.tar.gz
            curl -L $URL | tar zx
            [ -w /usr/local/bin ] && SUDO="" || SUDO=sudo
            $SUDO chmod +x ./kustomize
            $SUDO mv ./kustomize /usr/local/bin
      - checkout
      - run:
          name: Bump Docker Tag
          command: |
            git config user.email "$GITHUB_EMAIL"
            git config user.name "CircleCI User"
            git checkout $CIRCLE_BRANCH
            git pull origin $CIRCLE_BRANCH
            cd manifests
            kustomize edit set image restaurant-reservation=restaurant-reservation:$CIRCLE_BUILD_NUM
      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT"
      - run:
          name: Commit & Push to GitHub
          command: |
            git config user.email "$GITHUB_EMAIL"
            git config user.name "CircleCI User"
            git checkout $CIRCLE_BRANCH  
            git add manifests/kustomization.yaml
            git commit -am "Bumps docker tag [skip ci]"
            git push origin $CIRCLE_BRANCH

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: restaurant-reservation
          tag: $CIRCLE_BUILD_NUM
      - bump-docker-tag-kustomize:
          requires:
            - aws-ecr/build-and-push-image
      - argocd-configure:
          requires:
            - bump-docker-tag-kustomize
      - argocd-manual-sync:
          server: $ARGOCD_SERVER
          username: $ARGOCD_USERNAME
          password: $ARGOCD_PASSWORD
          requires:
            - argocd-configure
