version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

workflows:
  build_and_push:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: restaurant-reservation
          tag: $CIRCLE_BUILD_NUM
